project.name=intyg

artifact.name=statistik
artifact.version=8.1.0.3

sbom.aggregation.module=statistik-web
sbom.aggregation.path=web

git.url=https://github.com/sklintyg/statistik.git
git.branch=main

builder.image=app-builder-image
builder.image.tag=21.0.6

runtime.image=tomcat-base
runtime.image.tag=10.1.52.1

dependencies.infra.version=4.1.0.+

dependencies.infra.version.resolved=4.1.0.2

build.args=build testAggregateTestReport -PuseMinifiedJavaScript
sonarqube.args=-PuseNoMinifiedJavaScriptNoKarma