---

- name: stop tomcat
  service:
    name: "{{ tomcat_service }}"
    state: stopped

- name: create release directory
  file:
    path: "{{ releases_folder }}"
    state: directory

- name: Make sure liquibase runner file download is forced when using shapshot repo
  file:
    state: absent
    path: "{{ releases_folder }}/liquibase-runner-{{ version }}.zip"
  when: repo == "snapshots"

- name: Download liquibase-runner-{{ version }}.zip
  get_url:
    url: "https://build-inera.nordicmedtest.se/nexus/repository/{{ repo }}/se/inera/statistik/liquibase-runner/{{ version }}/liquibase-runner-{{ version }}.zip"
    dest: "{{ releases_folder }}/liquibase-runner-{{ version }}.zip"
  when: deploy_from_repo|bool

- name: Copy liquibase-runner-{{ version }}.zip from THIS machine
  copy:
    src: "{{ playbook_dir }}/../tools/liquibase-runner/build/distributions/liquibase-runner-{{ version }}.zip"
    dest: "{{ releases_folder }}/liquibase-runner-{{ version }}.zip"
  when: not deploy_from_repo|bool

- name: Make sure liquibase runner file unzip is forced when using shapshot repo
  file:
    state: absent
    path: "{{ releases_folder }}/liquibase-runner-{{ version }}"
  when: repo == "snapshots"

- name: Unzip liquibase-runner-{{ version }}.zip
  command: unzip -d {{ releases_folder }} {{ releases_folder }}/liquibase-runner-{{ version }}.zip
  args:
    creates: "{{ releases_folder }}/liquibase-runner-{{ version }}/bin/liquibase-runner"

- name: run liquibase update
  command: "{{ releases_folder }}/liquibase-runner-{{ version }}/bin/liquibase-runner --url={{ database_url }} --username={{ database_username }} --password={{ database_password }} update"
  args:
      chdir: "{{ releases_folder }}/liquibase-runner-{{ version }}"
  environment:
      JAVA_HOME: "{{ java_home }}"

- name: Make sure highcharts-export-web-{{ highcharts_version }} file download is forced when using shapshot repo
  file:
    state: absent
    path: "{{ releases_folder }}/highcharts-export-web-{{ highcharts_version }}.war"
  when: repo == "snapshots"

- name: Download highcharts-export-web-{{ highcharts_version }}.war
  get_url:
    url: "https://build-inera.nordicmedtest.se/nexus/repository/releases/com/highcharts/export/highcharts-export-web/{{ highcharts_version }}/highcharts-export-web-{{ highcharts_version }}.war"
    dest: "{{ releases_folder }}/highcharts-export-web-{{ highcharts_version }}.war"

- name: Make sure statistik-web file download is forced when using shapshot repo
  file:
    state: absent
    path: "{{ releases_folder }}/statistik-web-{{ version }}.war"
  when: repo == "snapshots"

- name: Download statistik-web-{{ version }}.war
  get_url:
    url: "https://build-inera.nordicmedtest.se/nexus/repository/{{ repo }}/se/inera/statistik/statistik-web/{{ version }}/statistik-web-{{ version }}.war"
    dest: "{{ releases_folder }}/statistik-web-{{ version }}.war"
  when: deploy_from_repo|bool

- name: Copy statistik-web-{{ version }}.war from THIS machine
  copy:
    src: "{{ playbook_dir }}/../statistik-web/build/libs/statistik-web-{{ version }}.war"
    dest: "{{ releases_folder }}/statistik-web-{{ version }}.war"
  when: not deploy_from_repo|bool

- name: remove old version of unpacked ROOT war
  file:
    state: absent
    path: "{{ tomcat_webapps }}/ROOT"

- name: remove old version of ROOT war
  file:
    state: absent
    path: "{{ tomcat_webapps }}/ROOT.war"

- name: remove old version of unpacked highchart war
  file:
    state: absent
    path: "{{ tomcat_webapps }}/highcharts-export-web"

- name: remove old version of highchart war
  file:
    state: absent
    path: "{{ tomcat_webapps }}/highcharts-export-web.war"

- name: Deploy statistik-web-{{ version }}.war as ROOT.war
  copy:
    src: "{{ releases_folder }}/statistik-web-{{ version }}.war"
    dest: "{{ tomcat_webapps }}/ROOT.war"

- name: Extract ROOT.war
  command: unzip -d {{ tomcat_webapps }}/ROOT {{ tomcat_webapps }}/ROOT.war
  args:
    creates: "{{ tomcat_webapps }}/ROOT"

- name: Deploy highchart-export-web-{{ highcharts_version }}.war
  copy:
    src: "{{ releases_folder }}/highcharts-export-web-{{ highcharts_version }}.war"
    dest: "{{ tomcat_webapps }}/highcharts-export-web.war"

- name: Remove statistik-web-{{ version }}.war from releases
  file:
    state: absent
    path: "{{ releases_folder }}/statistik-web-{{ version }}.war"

- name: Remove highchart-export-web-{{ highcharts_version }}.war from releases
  file:
    state: absent
    path: "{{ releases_folder }}/highcharts-export-web-{{ highcharts_version }}.war"

- name: Remove liquibase-runner-{{ version }}.zip from releases
  file:
    state: absent
    path: "{{ releases_folder }}/liquibase-runner-{{ version }}.zip"

- name: update configuration to {{ config_version }}
  git:
    repo: "{{ config_repository }}"
    dest: "{{ config_folder }}"
    version: "{{ config_version }}"

- name: Include host in login url
  replace:
    dest: "{{ tomcat_webapps }}/ROOT/WEB-INF/application-context-security.xml"
    regexp: '<property name="defaultTargetUrl" value="/#/verksamhet"/>'
    replace: '<property name="defaultTargetUrl" value="{{ host_url }}/#/verksamhet"/>'

- name: Include host in logout url
  replace:
    dest: "{{ tomcat_webapps }}/ROOT/WEB-INF/application-context-security.xml"
    regexp: '<security:logout logout-url="/saml/logout" logout-success-url="/" invalidate-session="true"/>'
    replace: '<security:logout logout-url="/saml/logout" logout-success-url="{{ host_url }}/" invalidate-session="true"/>'

- name: start tomcat
  service:
    name: "{{ tomcat_service }}"
    state: started
