# This playbook deploys Statistik

- hosts: all
  sudo: yes
  vars:
    # repo - values: snapshots or release
    repo: snapshots

    # latest release: XXX
    # latest snapshot: XXX
    version: 3.1.0-SNAPSHOT
    config_version: master
    highcharts_version: 2.1.0

  roles:
    - statistik
    - statistik-hsafileservice
