# This playbook deploys Statistik

- hosts: all
  sudo: yes
  vars:
    # repo - values: snapshot or release
    repo: release

    # latest release: XXX
    # latest snapshot: XXX
    version: 2.0.7
    config_version: master

  roles:
    - statistik
